import { test, expect } from '@playwright/test'
test('desktop conversations, sending, replies, edits, reactions, polls and persistence', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'General', exact: true })).toBeVisible()
  await page.getByRole('textbox', { name: 'Message composer' }).fill('An actual message from the browser test')
  await page.getByRole('button', { name: 'Send message', exact: true }).click()
  const sent = page.locator('article').filter({ has: page.locator('.message-text').filter({ hasText: 'An actual message from the browser test' }) })
  await expect(sent).toBeVisible()
  await sent.hover()
  await sent.getByRole('button', { name: 'Reply to message', exact: true }).click()
  await page.getByRole('textbox', { name: 'Message composer' }).fill('A reply with context')
  await page.getByRole('button', { name: 'Send message', exact: true }).click()
  await expect(page.locator('article').filter({ hasText: 'A reply with context' }).locator('.reply-preview')).toContainText('An actual message')
  await sent.hover()
  await sent.getByRole('button', { name: 'Message actions' }).click()
  await page.getByRole('menuitem', { name: 'Edit', exact: true }).click()
  await page.getByRole('textbox', { name: 'Message composer' }).fill('Edited browser message')
  await page.getByRole('button', { name: 'Send message', exact: true }).click()
  await expect(page.locator('article').filter({ hasText: 'Edited browser message' })).toContainText('(edited)')
  const edited = page.locator('article').filter({ hasText: 'Edited browser message' }).filter({ hasNot: page.locator('.reply-preview') })
  await edited.hover()
  await edited.getByRole('button', { name: 'React to message', exact: true }).click()
  await page.getByRole('button', { name: 'Choose 💚', exact: true }).click()
  await expect(edited.locator('.reaction')).toContainText('1')
  await edited.locator('.reaction').click()
  await expect(edited.locator('.reaction')).toHaveCount(0)
  await page.getByRole('button', { name: 'More composer actions' }).click()
  await page.getByRole('menuitem', { name: 'Create a poll' }).click()
  await page.getByRole('textbox', { name: /^Question/ }).fill('Does the poll work?')
  await page.getByRole('textbox', { name: /^Answers/ }).fill('Yes\nAbsolutely')
  await page.getByRole('button', { name: 'Create poll', exact: true }).click()
  const poll = page.locator('.poll-card').filter({ hasText: 'Does the poll work?' })
  await poll.getByRole('button', { name: /Absolutely/ }).click()
  await expect(poll).toContainText('1 votes')
  await page.reload()
  await expect(page.locator('.message-text').filter({ hasText: 'Edited browser message' })).toBeVisible()
  expect(errors).toEqual([])
})
test('account isolation, draft isolation, room creation, settings and global search', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('textbox', { name: 'Message composer' }).fill('Personal draft')
  await page.getByRole('button', { name: 'Switch to Alex · Work', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Team lounge', exact: true })).toBeVisible()
  await expect(page.getByRole('textbox', { name: 'Message composer' })).toHaveValue('')
  await expect(page.getByText('Personal draft', { exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Switch to Alex Morgan', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Message composer' })).toHaveValue('Personal draft')
  await page.getByRole('button', { name: 'New conversation', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Create a room', exact: true }).click()
  await page.getByRole('textbox', { name: /^Room name/ }).fill('Browser room')
  await page.getByRole('textbox', { name: 'Topic', exact: true }).fill('A new space')
  await page.getByRole('button', { name: 'Create room', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Browser room', exact: true })).toBeVisible()
  await page.keyboard.press('Control+k')
  await page.getByRole('searchbox', { name: 'Find a conversation', exact: true }).fill('Maya')
  await page.getByRole('dialog').getByRole('button', { name: /Maya Chen/ }).click()
  await expect(page.getByRole('heading', { name: 'Maya Chen', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Open settings' }).click()
  await page.getByRole('button', { name: 'Security', exact: true }).click()
  await expect(page.getByText('LOCAL-DEMO', { exact: true })).toBeVisible()
})
test('phone navigation, room details and sending have no horizontal overflow', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await expect(page.getByRole('searchbox', { name: 'Search conversations' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'General', exact: true })).not.toBeVisible()
  await page.locator('.room-item').filter({ hasText: 'General' }).click()
  await expect(page.getByRole('heading', { name: 'General', exact: true })).toBeVisible()
  await page.getByRole('textbox', { name: 'Message composer' }).fill('Hello from mobile')
  await page.getByRole('button', { name: 'Send message', exact: true }).click()
  await expect(page.getByText('Hello from mobile', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Room information' }).click()
  await expect(page.getByRole('complementary', { name: 'Room details' })).toBeVisible()
  await page.getByRole('button', { name: 'Close room details' }).click()
  await page.getByRole('button', { name: 'Back to conversations' }).click()
  await expect(page.getByRole('searchbox', { name: 'Search conversations' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})
test('vendored Matrix Rust SDK WASM initializes in a real browser', async ({ page }) => {
  await page.goto('/')
  const result = await page.evaluate(async () => {
    // @ts-expect-error Browser imports are resolved by the Vite development server.
    const { loadSdk } = await import('/src/sdk/engine.ts')
    const sdk = await loadSdk()
    const builder = new sdk.ClientBuilder()
    return { builder: typeof builder.build, indexedDb: typeof sdk.IndexedDbStoreBuilder, send: typeof sdk.MessageType.Text, sync: typeof sdk.SlidingSyncVersionBuilder.DiscoverNative }
  })
  expect(result).toMatchObject({ builder: 'function', indexedDb: 'function', send: 'function' })
})
