import { test, expect } from '@playwright/test'

test('account search finds messages across rooms and jumps', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'General', exact: true })).toBeVisible()
  await page.getByRole('textbox', { name: 'Message composer' }).fill('Zebra crossing plans for General')
  await page.getByRole('button', { name: 'Send message', exact: true }).click()
  await page.locator('.room-item', { has: page.locator('strong', { hasText: /^Design$/ }) }).click()
  await expect(page.getByRole('heading', { name: 'Design', exact: true })).toBeVisible()
  await page.getByRole('textbox', { name: 'Message composer' }).fill('Zebra sketches for Design')
  await page.getByRole('button', { name: 'Send message', exact: true }).click()
  await page.getByRole('button', { name: 'Search messages' }).click()
  await page.getByRole('button', { name: 'All rooms', exact: true }).click()
  await page.getByRole('searchbox', { name: 'Search messages' }).fill('zebra')
  await expect(page.getByRole('option', { name: 'Jump to message in General' })).toBeVisible()
  await expect(page.getByRole('option', { name: 'Jump to message in Design' })).toBeVisible()
  await page.getByRole('option', { name: 'Jump to message in General' }).click()
  await expect(page.getByText('Viewing message context')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'General', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Back to live' }).click()
  await expect(page.getByText('Viewing message context')).toHaveCount(0)
  expect(errors).toEqual([])
})
test('pins tab lists, jumps and unpins', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'General', exact: true })).toBeVisible()
  const target = page.locator('article').filter({ hasText: 'A quieter kind of workspace' }).first()
  await target.hover()
  await target.getByRole('button', { name: 'Message actions' }).click()
  await page.getByRole('menuitem', { name: 'Pin message' }).click()
  await page.getByRole('button', { name: 'Room information' }).click()
  await page.getByRole('button', { name: 'Pins', exact: true }).click()
  const details = page.getByRole('complementary', { name: 'Room details' })
  await expect(details.getByText('A quieter kind of workspace')).toBeVisible()
  await page.getByRole('button', { name: 'Jump to pinned message' }).click()
  await expect(page.getByText('Viewing message context')).toBeVisible()
  await page.getByRole('button', { name: 'Back to live' }).click()
  await page.getByRole('button', { name: 'Room information' }).click()
  await page.getByRole('button', { name: 'Pins', exact: true }).click()
  await page.getByRole('button', { name: /^Unpin message/ }).click()
  await expect(page.getByText('No pinned messages in this room yet.')).toBeVisible()
})
test('media tab filters gallery and jumps', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'General', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Room information' }).click()
  await page.getByRole('button', { name: 'Media', exact: true }).click()
  const media = page.getByRole('complementary', { name: 'Room details' })
  await expect(media.getByText('Design principles.md')).toBeVisible()
  await media.getByRole('group', { name: 'Gallery filter' }).getByRole('button', { name: 'Media', exact: true }).click()
  await expect(media.getByText('Design principles.md')).toHaveCount(0)
  await media.getByRole('button', { name: 'Files', exact: true }).click()
  await expect(media.getByText('Design principles.md')).toBeVisible()
  await media.getByRole('button', { name: 'All', exact: true }).click()
  const row = media.locator('.shared-file', { hasText: 'Design principles.md' })
  await row.getByRole('button', { name: 'Jump to message' }).click()
  await expect(page.getByText('Viewing message context')).toBeVisible()
})
